import type { Metadata } from 'next'
import './globals.css'
import './homepage.css'

export const metadata: Metadata = {
  title: 'Blog app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
};
