import type { Metadata } from 'next'
import './globals.css'
import './homepage.css'
import LanguageSwitcher from '../components/language-switcher/language-switcher'

export const metadata: Metadata = {
  title: 'Blog app',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
  params
}: {
  children: React.ReactNode,
  params: {locale: string} 
}) {
  return (
    <html lang={params.locale}>
      <body>
        <LanguageSwitcher currentLanguage={params.locale} />
        {children}
      </body>
    </html>
  );
};
